### ISSUE TITLE
Filter 'the_nimble_tinymce_module_content' makes it impossible for a method run on wp_enqueue_scripts to find shortcodes and enqueue resources

### ISSUE THREAD

**Issue by bowens** [presscustomizr/nimble-builder#836]
I'm working with NextGEN Gallery in particular.

NGG enqueues gallery JS/CSS by a method registered to `wp_enqueue_scripts` that examines the global `$post->post_content` to determine which modules' resources to load. With Nimble Builder shortcode blocks `post_content` is empty and I can't find a way to correctly enqueue our resources.

This is probably related to issue #233

**Comment by Nikeo** [comment]
Hello,
Thanks for reporting this issue. I have been receiving requests from users who had difficulties to use NGG with Nimble Builder. Like here : https://wordpress.org/support/topic/nextgen-will-not-work-with-nimblebuilder-2/

Nimble builder doesn't use the `post_content` to store its content. `the_nimble_tinymce_module_content` is not the right candidate to detect NGG shortcode. This filter allows NB to apply the various filters normally applied by WP core on 'the_content' but without risking to be modified by a third party plugin. ( that's the problem pointed and solved in #233 )

To detect NGG shortcode ( and determine if NGG should enqueue its assets ), you'll need to fetch the contextual content created in NB, which is not necessary a page or a post, but could be a category page, an author page, a 404 page etc.. 
NB function to get the content in any page is \Nimble\sek_get_skoped_seks(). To make it simpler and more readable, I've introduced an helper function which returns the contextual NB content as a json : `nimble_get_content_as_json()`. See https://github.com/presscustomizr/nimble-builder/commit/f61c5702946f20bad283115796236ad547bcfb8d
This function can be used in any page of a website, after `wp` hook has been fired by WordPress. So you'll be able to use it at `wp_enqueue_scripts`.

Detecting if a NGG shortcode has been inserted with NB can therefore be done like it is done here : https://github.com/imagely/nextgen-gallery/blob/master/products/photocrati_nextgen/modules/nextgen_gallery_display/module.nextgen_gallery_display.php#L112

`preg_match_all('/' . get_shortcode_regex() . '/', nimble_get_content_as_json(), $matches, PREG_SET_ORDER);`

You can test this solution with the next version of NB, available here : https://github.com/presscustomizr/nimble-builder/releases/tag/v3.1.5-beta

**Comment by bowens** [comment]
Excellent, thank you! I'll try to have this resolved finally in the next NGG release.
